[build]
  builder = "dockerfile"
  dockerfilePath = "backend.Dockerfile"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[variables]
  PORT = "8080"
  DB_HOST = "${{PGHOST}}"
  DB_PORT = "${{PGPORT}}"
  DB_USER = "${{PGUSER}}"
  DB_PASSWORD = "${{PGPASSWORD}}"
  DB_NAME = "${{PGDATABASE}}"