[build]
  builder = "dockerfile"
  dockerfilePath = "backend.Dockerfile"

[deploy]
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[variables]
  PORT = "8080"